#------------------------2026年3月16日---------------------------#
name: Scan Files and update list

on:
    push:
        paths:
            - 'Downloads/**'
            - 'Scripts/scan-files.py'

    schedule:
        - cron: '0 2 * * *'

    workflow_dispatch:

jobs:
    scan-files:
        runs-on: ubuntu-latest

        